@echo on
cd "c:\ProgramData\Lenovo\LenovoTvtTools"
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\en-US\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\cs-CZ\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\da-DK\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\de-DE\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\el-GR\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\es-ES\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\fi-FI\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\fr-FR\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\he-IL\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\hu-HU\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\it-IT\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\ja-JP\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\ko-KR\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\nb-NO\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\nl-NL\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\pl-PL\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\pt-BR\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\pt-PT\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\ru-RU\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\sl-SI\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\sv-SE\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\tr-TR\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\zh-CN\*.devicemetadata-ms
del /f /q   C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\zh-TW\*.devicemetadata-ms
xcopy /Y .\en-US\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\en-US\*.devicemetadata-ms
xcopy /Y .\cs-CZ\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\cs-CZ\*.devicemetadata-ms
xcopy /Y .\da-DK\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\da-DK\*.devicemetadata-ms
xcopy /Y .\de-DE\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\de-DE\*.devicemetadata-ms
xcopy /Y .\el-GR\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\el-GR\*.devicemetadata-ms
xcopy /Y .\es-ES\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\es-ES\*.devicemetadata-ms
xcopy /Y .\fi-FI\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\fi-FI\*.devicemetadata-ms
xcopy /Y .\fr-FR\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\fr-FR\*.devicemetadata-ms
xcopy /Y .\he-IL\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\he-IL\*.devicemetadata-ms
xcopy /Y .\hu-HU\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\hu-HU\*.devicemetadata-ms
xcopy /Y .\it-IT\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\it-IT\*.devicemetadata-ms
xcopy /Y .\ja-JP\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\ja-JP\*.devicemetadata-ms
xcopy /Y .\ko-KR\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\ko-KR\*.devicemetadata-ms
xcopy /Y .\nb-NO\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\nb-NO\*.devicemetadata-ms
xcopy /Y .\nl-NL\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\nl-NL\*.devicemetadata-ms
xcopy /Y .\pl-PL\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\pl-PL\*.devicemetadata-ms
xcopy /Y .\pt-BR\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\pt-BR\*.devicemetadata-ms
xcopy /Y .\pt-PT\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\pt-PT\*.devicemetadata-ms
xcopy /Y .\ru-RU\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\ru-RU\*.devicemetadata-ms
xcopy /Y .\sl-SI\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\sl-SI\*.devicemetadata-ms
xcopy /Y .\sv-SE\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\sv-SE\*.devicemetadata-ms
xcopy /Y .\tr-TR\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\tr-TR\*.devicemetadata-ms
xcopy /Y .\zh-CN\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\zh-CN\*.devicemetadata-ms
xcopy /Y .\zh-TW\*.devicemetadata-ms C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\zh-TW\*.devicemetadata-ms
